<a href="https://colab.research.google.com/github/samestediazmedin/CARROS/blob/main/Practico_Lectura_de_Exel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [6]:
part = "/datos_rrss.xlsx"

In [9]:
pd.read_excel(part
              )

      Nombre  Cantidad  ES_FBK   Año
0   Facebook      2449    True  2006
1    Twitter       339   False  2006
2  Instagram      1000    True  2010
3    YouTube      2000   False  2005
4   LinkedIn       663   False  2003
5   WhatsApp      1600    True  2009

In [8]:
pd.read_excel(part, sheet_name="Hoja2")

      Nombre  Cantidad  ES_FBK   Año
0   Facebook      2449    True  2006
1    Twitter       339   False  2006
2  Instagram      1000    True  2010

In [17]:
pd.read_excel(part,

              sheet_name="Hoja3",
              header= None,
              names=["Nombre", "cantidad", "es_F O V", "Año"]

              )

      nombre  cantidad  es_F O V   Año
0   Facebook      2449      True  2006
1    Twitter       339     False  2006
2  Instagram      1000      True  2010
3    YouTube      2000     False  2005
4   LinkedIn       663     False  2003
5   WhatsApp      1600      True  2009

## Uploading Project to Git

To upload this Colab project to your Git repository, you can use the following shell commands. Please ensure you execute these commands in a code cell.

1.  **Initialize Git:** If this is a new repository or you haven't initialized Git in your Colab environment for this project, you'll need to run `git init`.
2.  **Configure Git:** Set your user name and email for Git commits.
3.  **Add Files:** Add all relevant files to the Git staging area.
4.  **Commit Changes:** Commit the staged changes with a descriptive message.
5.  **Add Remote:** Link your local repository to the remote GitHub repository.
6.  **Push to Main:** Push your committed changes to the `main` branch of your remote repository. If the branch doesn't exist, it will be created.

In [21]:
import os

# Change to the content directory if not already there
if not os.getcwd().endswith('/content'):
    os.chdir('/content')

# Initialize Git (reinitializes if it exists, ensures a clean state)
!git init

# Configure user name and email
!git config user.email "18samuelmedina@gmail.com"
!git config user.name "samestediazmedin"

# Add all files to the staging area
!git add .

# Rename the branch from 'master' to 'main'
# This ensures consistency with modern GitHub repositories.
!git branch -M main

# Commit the changes (will report "nothing to commit" if no new changes)
!git commit -m "Initial commit from Colab"

# Remove the remote 'origin' if it already exists, to prevent 'remote origin already exists' error
!git remote remove origin || true

# Add the remote repository
!git remote add origin https://github.com/samestediazmedin/ejercicios-bit-data-anality.git

# Push to the main branch using a Personal Access Token (PAT) for authentication.
# REPLACE <YOUR_PERSONAL_ACCESS_TOKEN> with your actual GitHub PAT.
# See instructions above on how to generate a PAT.
!git push -u https://<YOUR_PERSONAL_ACCESS_TOKEN>@github.com/samestediazmedin/ejercicios-bit-data-anality.git main

Reinitialized existing Git repository in /content/.git/
On branch main
nothing to commit, working tree clean
/bin/bash: line 1: YOUR_PERSONAL_ACCESS_TOKEN: No such file or directory

In [22]:
!git log

commit 92387a7b77eab45ce0a6b96358e5f69fd65ca63b (HEAD -> main)
Author: samestediazmedin <18samuelmedina@gmail.com>
Date:   Sat May 23 02:09:27 2026 +0000

    Initial commit from Colab

# Nueva sección